#!/usr/bin/env python3
"""
install.py — AMG installer (Stage 10). The successor to sync_testbed.py.

Deterministic and config-driven: the MODEL conducts the Q&A (see INSTALL.md) and calls
this with the answers; the script does the file work — copy the engine, render the entry
templates per agent_dir/entrypoint, inject the activation block between markers, merge
settings.json, seed digest.md, write config.yml, render the models block into agent
frontmatter, optionally install deps, and verify the store. It NEVER builds the graph:
activation is the user's choice (a question the model
asks), and even when active the structural build runs from the activation loop or
`/amg sync`, never as an install side effect — so installing/activating does not silently
index a whole project.

Local vs global engine; the graph is ALWAYS local:
  local  : engine -> <target>/<agent_dir>/{skills,agents}; block -> <target>/<entrypoint>
  global : engine -> ~/<agent_dir>/{skills,agents};        block -> ~/<entrypoint>, with
           ABSOLUTE engine paths in it. Each project still gets its own local
           <target>/<agent_dir>/amg graph + config.yml; graphs are never shared.

Control-plane mechanics (hooks, the /amg slash command, the @digest import) are Claude
Code features. In another environment the portable substrate is the activation loop plus
verbal triggers plus direct script calls; the block carries that loop regardless.

CLI (the model fills these from the user's answers):
  python install.py --target <proj> [--scope local|global]
      [--agent-dir .claude] [--entrypoint CLAUDE.md]
      [--env claude-code|generic]   # generic = any other agent env (Codex, Qwen Coder, ...):
                                    # the portable skill-less AGENTS.md block, no hooks/command
      [--mirror a,b] [--absorb c,d] [--exclude "*.x,*.y"]
      [--set active=false] [--set working_language=ru] [--set automation=true] ...
      [--deps base,embeddings,text,treesitter] [--no-verify]
      [--build]          # also build the structural graph now (ready this session)
      [--project-only]   # add a project to an existing (global) install: local config only
  python install.py --target <proj> --uninstall [--scope global] [--purge-graph]

Reinstall is safe and idempotent: only the AMG skills/agents are replaced (other skills
in a shared ~/.claude are kept), the block is refreshed between its markers, and an
existing project config.yml is never clobbered. Project graphs are always local, so a
global reinstall never touches them.
"""
from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Optional

try:
    import yaml
except ImportError:                                   # pragma: no cover
    yaml = None                                       # model-tiering render needs PyYAML

REPO = Path(__file__).resolve().parent
SKILL_NAMES = ("amg-bootstrap", "amg-retrieve", "amg-consolidate")
BEGIN = "<!-- AMG:BEGIN -->"
END = "<!-- AMG:END -->"

DIGEST_PLACEHOLDER = (
    "<!-- AMG memory digest — auto-generated by consolidation; do not edit by hand. -->\n"
    "## AMG memory digest — standing decisions & open questions\n\n"
    "_No active decisions or open questions captured yet._\n")

# Optional dependency groups (also documented in requirements.txt). base is the only
# hard requirement; the rest degrade gracefully when absent.
DEP_GROUPS = {
    "base": ["pyyaml"],
    "embeddings": ["model2vec"],
    "embeddings-st": ["sentence-transformers"],
    "text": ["pypdf", "python-docx", "openpyxl", "python-pptx"],
    "treesitter": ["tree-sitter", "tree-sitter-language-pack"],
}


# --------------------------------------------------------------------------- #
# Path rendering: the templates carry the Claude Code default `.claude`, rendered
# per agent_dir/entrypoint. For a GLOBAL install the ENGINE (skills/agents) lives in
# the home dir, so its script paths become absolute, while the GRAPH (amg/) stays
# project-local.
# --------------------------------------------------------------------------- #

def _engine_abs(agent_dir: str) -> str:
    """Absolute home-based engine dir for a global install, POSIX-style so the path
    works in both bash and PowerShell command lines."""
    return (Path.home() / agent_dir).as_posix()


def _env_kind(env: str) -> str:
    """Classify the target agent environment into one of three install modes:
      claude-code — skills + subagents + SessionStart/SessionEnd hooks + /amg command;
      codex       — OpenAI Codex: HAS skills (.agents/skills) + subagents (TOML in
                    .codex/agents), but no Claude hooks / slash command / @import;
      generic     — any other AGENTS.md env (Qwen Coder, ...): the portable SKILL-LESS
                    block, model-driven via direct script calls."""
    e = env.strip().lower()
    if e in ("claude-code", "claude", "cc", ""):
        return "claude-code"
    if e in ("codex", "openai-codex"):
        return "codex"
    return "generic"


def _is_claude_code(env: str) -> bool:
    return _env_kind(env) == "claude-code"


def render_control_text(text: str, agent_dir: str, entrypoint: str,
                        scope: str) -> str:
    """Render `.claude`/`CLAUDE.md` literals in a control-plane file. ENGINE script
    paths (.claude/skills, .claude/agents) point at the install location (absolute for
    global); GRAPH paths (.claude/amg) and the digest import stay project-local."""
    if scope == "global":
        eng = _engine_abs(agent_dir)
        # The @digest import is resolved by Claude Code relative to the (global) entry
        # file, so it cannot point at a per-project graph — replace it with a loop note.
        text = re.sub(r"(?m)^@\.claude/amg/digest\.md\s*$",
                      f"<!-- per-project digest: the loop reads {agent_dir}/amg/digest.md "
                      f"at session start (a global entry file cannot @import it) -->", text)
        text = text.replace(".claude/skills", f"{eng}/skills")
        text = text.replace(".claude/agents", f"{eng}/agents")
    text = text.replace("@.claude/amg", f"@{agent_dir}/amg")     # local digest import
    text = text.replace(".claude", agent_dir)                    # graph + remaining paths
    text = text.replace("CLAUDE.md", entrypoint)
    return text


def _block_body(template_text: str) -> str:
    """The activation block to inject: the entry template minus any standalone
    `# Project memory` preamble (framing for the wholesale dev/testbed copy, redundant
    inside a user's existing entry file). Start at the first `## ` heading."""
    idx = template_text.find("\n## ")
    return template_text[idx + 1:].rstrip() if idx != -1 else template_text.strip()


def inject_block(entry_path: Path, block: str) -> str:
    """Write the activation block between the AMG markers, preserving the user's own
    content above and below. Reinstall replaces only the marked region (idempotent)."""
    wrapped = f"{BEGIN}\n{block.strip()}\n{END}"
    if entry_path.exists():
        text = entry_path.read_text(encoding="utf-8")
        pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
        if pat.search(text):
            new = pat.sub(lambda _m: wrapped, text)
        else:
            new = text.rstrip() + "\n\n" + wrapped + "\n"
    else:
        new = wrapped + "\n"
    entry_path.parent.mkdir(parents=True, exist_ok=True)
    entry_path.write_text(new, encoding="utf-8")
    return new


# --------------------------------------------------------------------------- #
# settings.json hooks: MERGE, never clobber
# --------------------------------------------------------------------------- #

def _is_amg_hook(entry: dict) -> bool:
    """An AMG lifecycle hook entry (so reinstall replaces ours, keeps the user's)."""
    for h in (entry or {}).get("hooks", []):
        if "lifecycle.py" in str(h.get("command", "")):
            return True
    return False


def merge_settings(dest_path: Path, template_obj: dict) -> None:
    """Merge AMG's SessionStart/SessionEnd hooks into an existing settings.json without
    dropping the user's own hooks or other keys. Replaces any prior AMG hook entries."""
    existing: dict = {}
    if dest_path.exists():
        try:
            existing = json.loads(dest_path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            existing = {}
    hooks = existing.setdefault("hooks", {})
    for event, entries in (template_obj.get("hooks") or {}).items():
        cur = [e for e in hooks.get(event, []) if not _is_amg_hook(e)]
        cur.extend(entries)
        hooks[event] = cur
    dest_path.parent.mkdir(parents=True, exist_ok=True)
    dest_path.write_text(json.dumps(existing, indent=2) + "\n", encoding="utf-8")


# --------------------------------------------------------------------------- #
# config.yml: copy the shipped template, fill the answered keys (preserve comments)
# --------------------------------------------------------------------------- #

# A real config key line: `key:` (or a commented-out `# key:`) at column 0, the colon
# immediately after the key. This deliberately does NOT match prose in the template's
# header comments (e.g. `#   mirror_path : the graph is a LIVE PROJECTION ...`), which
# is indented and has a space before the colon — matching it would inject a duplicate key.
def _keyline(key: str) -> "re.Pattern[str]":
    return re.compile(rf"^(# ?)?{re.escape(key)}:")


def _set_scalar(text: str, key: str, value: str) -> str:
    """Set a top-level scalar key (commented or not) in place; append if missing."""
    pat = re.compile(rf"(?m)^(# ?)?{re.escape(key)}:.*$")
    new, n = pat.subn(lambda _m: f"{key}: {value}", text, count=1)
    return new if n else text.rstrip() + f"\n{key}: {value}\n"


def _set_list(text: str, key: str, items: List[str]) -> str:
    """Replace a top-level list key (block, flow, or commented) with a flow list. Items
    are quoted, so globs like *.tmp stay valid YAML. Empty items -> leave unchanged."""
    if not items:
        return text
    flow = "[" + ", ".join(f'"{it}"' for it in items) + "]"
    keyline = _keyline(key)
    itemline = re.compile(r"^\s*#?\s*-\s")
    lines = text.split("\n")
    out: List[str] = []
    i, done = 0, False
    while i < len(lines):
        if not done and keyline.match(lines[i]):
            done = True
            i += 1
            while i < len(lines) and itemline.match(lines[i]):   # consume block items
                i += 1
            out.append(f"{key}: {flow}")
            continue
        out.append(lines[i])
        i += 1
    if not done:
        out.append(f"{key}: {flow}")
    return "\n".join(out)


def write_config(dest_amg: Path, agent_dir: str, entrypoint: str,
                 mirror: List[str], absorb: List[str], exclude: List[str],
                 scalars: Dict[str, str]) -> bool:
    """Create <agent_dir>/amg/config.yml from the shipped template, filling the answered
    keys. An EXISTING config is preserved (reinstall never clobbers a project's config).
    Returns True if written, False if left intact. agent_dir/entrypoint are always recorded
    so resolution and the docs agree with the install."""
    dest = dest_amg / "config.yml"
    if dest.exists():
        return False
    text = (REPO / "config.yml").read_text(encoding="utf-8")
    for key, value in scalars.items():
        text = _set_scalar(text, key, value)
    text = _set_list(text, "mirror_path", mirror)
    text = _set_list(text, "absorb_path", absorb)
    if exclude:
        text = _set_list(text, "exclude", exclude)
    text = _set_scalar(text, "agent_dir", agent_dir)
    text = _set_scalar(text, "entrypoint", entrypoint)
    if agent_dir != ".claude":               # render the one path-valued default (1.32)
        text = re.sub(r"(?m)^(\s*cases:\s*)\.claude/",
                      lambda m: m.group(1) + agent_dir + "/", text)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(text, encoding="utf-8")
    return True


# --------------------------------------------------------------------------- #
# Model tiering: render config.yml `models` into agent frontmatter (audit 1.14)
#
# config.yml `models` is the SINGLE SOURCE OF TRUTH for per-role model + reasoning
# effort; install (and reinstall) renders it into the installed agent definitions, so
# agents/*.md carry only the rendered result. Each role maps to one or more agents.
# A role value is a flat model string ("opus") or a {model, reasoning_effort} mapping.
#
# Known upstream caveat (Claude Code issue #44385): a subagent's frontmatter `model:`
# is currently IGNORED when the agent is spawned without an explicit model parameter
# (it inherits the parent model); the `effort` field IS honored. We still write
# `model:` as the documented, forward-compatible surface — to force a model today,
# pass it on the Agent call or set CLAUDE_CODE_SUBAGENT_MODEL.
# --------------------------------------------------------------------------- #

ROLE_AGENTS = {
    "discovery": ("amg-classifier", "amg-retriever"),
    "module_summary": ("amg-builder",),
    "synthesis": ("amg-synth", "amg-consolidator"),
    # structural_extraction is deterministic — no model, no agent.
}

# AMG's neutral `reasoning_effort` clamps to what each environment supports. Claude
# Code's subagent `effort` field is low|medium|high|xhigh|max (no `minimal`); Codex's
# `model_reasoning_effort` is minimal|low|medium|high|xhigh (no `max`).
_EFFORT_CLAMP = {
    "claude-code": {"minimal": "low", "low": "low", "medium": "medium",
                    "high": "high", "xhigh": "xhigh", "max": "max"},
    "codex": {"minimal": "minimal", "low": "low", "medium": "medium",
              "high": "high", "xhigh": "xhigh", "max": "xhigh"},
}


def _resolve_role(value: object) -> tuple[Optional[str], Optional[str]]:
    """A models.<role> entry is either a flat model string or a {model,
    reasoning_effort} mapping. Return (model, reasoning_effort); either may be None."""
    if isinstance(value, str):
        return (value.strip() or None), None
    if isinstance(value, dict):
        model = value.get("model")
        eff = value.get("reasoning_effort")
        return ((str(model).strip() or None) if model else None,
                (str(eff).strip() or None) if eff else None)
    return None, None


def _clamp_effort(effort: Optional[str], env: str) -> Optional[str]:
    """Map a neutral reasoning_effort level to the one this environment supports.
    Unknown level -> None (skip)."""
    if not effort:
        return None
    table = _EFFORT_CLAMP.get(_env_kind(env), _EFFORT_CLAMP["claude-code"])
    return table.get(effort.strip().lower())


def _set_agent_field(text: str, key: str, value: str) -> str:
    """Set `key: value` inside the YAML frontmatter (first --- ... --- block) of an
    agent markdown file, preserving description/tools and the body. Replaces the line
    if present, else appends it to the frontmatter. No frontmatter -> text unchanged."""
    m = re.match(r"(?s)^(---\n)(.*?)(\n---\n?)(.*)$", text)
    if not m:
        return text
    head, fm, close, body = m.groups()
    line = f"{key}: {value}"
    pat = re.compile(rf"(?m)^{re.escape(key)}:.*$")
    fm = pat.sub(line, fm, count=1) if pat.search(fm) else fm.rstrip() + "\n" + line
    return head + fm + close + body


def render_agent_models(agents_dir: Path, models_cfg: dict, env: str) -> None:
    """Render per-role model + reasoning effort from config.yml `models` into the
    installed agent frontmatter (Claude Code `model`/`effort`). Idempotent: reinstall
    re-copies the source agents, then this re-applies. A role given only a model gets no
    effort field (the model/tool default applies)."""
    if not isinstance(models_cfg, dict):
        return
    touched: List[str] = []
    for role, agents in ROLE_AGENTS.items():
        model, eff = _resolve_role(models_cfg.get(role))
        eff = _clamp_effort(eff, env)
        if model is None and eff is None:
            continue
        for ag in agents:
            f = agents_dir / f"{ag}.md"
            if not f.exists():
                continue
            text = f.read_text(encoding="utf-8")
            if model:
                text = _set_agent_field(text, "model", model)
            if eff:
                text = _set_agent_field(text, "effort", eff)
            f.write_text(text, encoding="utf-8")
            touched.append(ag)
    if touched:
        print(f"  models  rendered model/effort into {len(touched)} agent(s) from config.yml models")


def _read_models(config_path: Path) -> dict:
    """The `models` block from a config.yml (empty dict if absent/unreadable or
    PyYAML is missing)."""
    if yaml is None or not config_path.exists():
        return {}
    try:
        cfg = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
    except (OSError, ValueError):
        return {}
    return cfg.get("models") or {}


# Claude family aliases. For a CODEX install these in config.yml mean the unchanged
# Claude default (not a deliberate Codex model), so they are NOT written into the Codex
# TOML — Codex falls back to its session model; a real id (gpt-5.5, ...) passes through.
_CLAUDE_ALIASES = {"opus", "sonnet", "haiku", "fable", "best", "default", "opusplan"}


def _md_frontmatter_body(text: str) -> tuple[dict, str]:
    """Split an agent .md into (frontmatter dict, body)."""
    m = re.match(r"(?s)^---\n(.*?)\n---\n?(.*)$", text)
    if not m:
        return {}, text.strip()
    fm = (yaml.safe_load(m.group(1)) or {}) if yaml else {}
    return fm, m.group(2).strip()


def _toml_basic(s: str) -> str:
    """Escape a one-line TOML basic string."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def render_codex_agents(repo_agents_dir: Path, dest_dir: Path, models_cfg: dict,
                        env: str) -> List[str]:
    """Render agents/amg-*.md into Codex TOML subagents in <dest_dir> (.codex/agents).
    Each TOML carries name, description, developer_instructions (the prompt body, paths
    rendered to the codex skills/graph dir), and — from config.yml `models` — the
    reasoning effort and (when the configured model is a real id, not a Claude alias) the
    model. Codex honors these TOML fields; a subagent's .md frontmatter does not apply in
    Codex. Reinstall replaces the amg-*.toml set, never duplicating it."""
    agent_role = {a: r for r, ags in ROLE_AGENTS.items() for a in ags}
    dest_dir.mkdir(parents=True, exist_ok=True)
    for old in dest_dir.glob("amg-*.toml"):          # reinstall: replace, don't duplicate
        old.unlink()
    written: List[str] = []
    for ag in sorted(repo_agents_dir.glob("amg-*.md")):
        fm, body = _md_frontmatter_body(ag.read_text(encoding="utf-8"))
        name = str(fm.get("name") or ag.stem)
        desc = render_control_text(str(fm.get("description") or ""), ".agents",
                                   "AGENTS.md", "local").strip().replace("\n", " ")
        model, eff = _resolve_role(models_cfg.get(agent_role.get(name, "")))
        if model is None:
            model = fm.get("model")                  # fall back to the .md default
        eff = _clamp_effort(eff, env)
        # Render the prompt body's .claude paths to the codex skills/graph dir (.agents).
        instr = render_control_text(body, ".agents", "AGENTS.md", "local").replace("'''", "''")
        lines = [f'name = "{_toml_basic(name)}"', f'description = "{_toml_basic(desc)}"']
        if model and model not in _CLAUDE_ALIASES:
            lines.append(f'model = "{_toml_basic(str(model))}"')
        if eff:
            lines.append(f'model_reasoning_effort = "{_toml_basic(eff)}"')
        lines.append("developer_instructions = '''\n" + instr + "\n'''")
        (dest_dir / f"{name}.toml").write_text("\n".join(lines) + "\n", encoding="utf-8")
        written.append(name)
    if written:
        print(f"  codex   rendered {len(written)} TOML subagent(s) -> {dest_dir}")
    return written


# --------------------------------------------------------------------------- #
# Engine placement, digest seed, deps, verify
# --------------------------------------------------------------------------- #

def place_engine(dest_agent_dir: Path, agent_dir: str, entrypoint: str, scope: str,
                 env: str) -> None:
    """Install the engine, replacing ONLY the AMG skills and agents. A shared agent dir
    (especially a global ~/.claude) keeps the user's other skills and agents, and a
    reinstall refreshes just AMG. Never touches __pycache__.

    The shipped PROMPTS (each skill's SKILL.md and agents/*.md) carry `.claude`/`CLAUDE.md`
    as the Claude Code default and are RENDERED to the configured agent dir on copy, exactly
    like the entry templates (audit 1.32). Copying them verbatim would leave `.claude/...`
    command paths that are wrong under any other agent dir, and relative script paths that
    are wrong for a global install. (References/*.md stay verbatim — they are docs, neutralized
    at Stage 18.)"""
    skills_dest = dest_agent_dir / "skills"
    skills_dest.mkdir(parents=True, exist_ok=True)
    for sk in SKILL_NAMES:
        src = REPO / "skills" / sk
        if not src.is_dir():
            raise SystemExit(f"missing engine skill in repo: {src}")
        dest = skills_dest / sk
        if dest.exists():
            shutil.rmtree(dest)
        shutil.copytree(src, dest, ignore=shutil.ignore_patterns("__pycache__"))
        smd = dest / "SKILL.md"
        if smd.exists():
            smd.write_text(render_control_text(smd.read_text(encoding="utf-8"),
                                               agent_dir, entrypoint, scope), encoding="utf-8")
    if _env_kind(env) == "codex":
        return                       # codex subagents are rendered as TOML (render_codex_agents)
    agents_dest = dest_agent_dir / "agents"
    agents_dest.mkdir(parents=True, exist_ok=True)
    for ag in sorted((REPO / "agents").glob("amg-*.md")):
        agents_dest.joinpath(ag.name).write_text(
            render_control_text(ag.read_text(encoding="utf-8"), agent_dir, entrypoint, scope),
            encoding="utf-8")


def seed_digest(dest_amg: Path) -> None:
    """Seed an empty digest.md so the block's @import resolves before the first
    consolidation. Never overwrites a real digest."""
    dest_amg.mkdir(parents=True, exist_ok=True)
    digest = dest_amg / "digest.md"
    if not digest.exists():
        digest.write_text(DIGEST_PLACEHOLDER, encoding="utf-8")


def install_deps(groups: List[str]) -> None:
    """pip-install the requested optional groups (opt-in via --deps)."""
    pkgs: List[str] = []
    for g in groups:
        if g not in DEP_GROUPS:
            print(f"  deps: unknown group {g!r} (known: {', '.join(DEP_GROUPS)})")
            continue
        pkgs += DEP_GROUPS[g]
    if not pkgs:
        return
    print(f"  deps: pip install {' '.join(pkgs)}")
    subprocess.run([sys.executable, "-m", "pip", "install", *pkgs], check=False)


def verify_store(engine_agent_dir: Path, graph_agent_dir: Path) -> int:
    """Initialize and verify the LOCAL store with the INSTALLED engine (no graph build).
    engine_agent_dir holds skills/ (global: home); graph_agent_dir holds amg/ (project)."""
    gs = engine_agent_dir / "skills" / "amg-bootstrap" / "scripts" / "graph_store.py"
    root = str(graph_agent_dir)
    subprocess.run([sys.executable, str(gs), "init", "--root", root], check=False)
    r = subprocess.run([sys.executable, str(gs), "verify", "--repair", "--root", root])
    return r.returncode


def build_graph(engine_agent_dir: Path, project_root: Path, graph_agent_dir: Path) -> None:
    """Optionally build the STRUCTURAL graph now (--build), so the memory is ready in the
    same session instead of waiting for the activation loop. This is the deterministic
    skeleton only; semantic enrichment (summaries + edges) is model-driven (the
    amg-bootstrap skill / activation loop), since a script cannot run subagents."""
    rc = engine_agent_dir / "skills" / "amg-bootstrap" / "scripts" / "reconcile.py"
    print("  build   reconcile bootstrap (structural skeleton)")
    subprocess.run([sys.executable, str(rc), "bootstrap", str(project_root),
                    "--root", str(graph_agent_dir)], check=False)


# --------------------------------------------------------------------------- #
# Install / uninstall
# --------------------------------------------------------------------------- #

def install(target: Path, scope: str, agent_dir: str, entrypoint: str,
            mirror: List[str], absorb: List[str], exclude: List[str],
            scalars: Dict[str, str], deps: List[str], verify: bool,
            build: bool = False, project_only: bool = False,
            env: str = "claude-code") -> None:
    target = target.resolve()
    # project_only adds a project to an existing GLOBAL install, so the engine it
    # verifies/builds with lives in the home dir, not under the new project.
    engine_root = Path.home() if (scope == "global" or project_only) else target
    engine_agent_dir = engine_root / agent_dir
    graph_agent_dir = target / agent_dir                         # the graph is ALWAYS local
    entry_path = engine_root / entrypoint

    if project_only:
        # Add a project to an EXISTING (usually global) install: only the local config +
        # digest; the engine, block, hooks and command are already in place and untouched.
        print(f"add project to existing install -> graph {graph_agent_dir / 'amg'} (engine untouched)")
    else:
        kind = _env_kind(env)
        print(f"install AMG ({scope}, env={env}) -> engine {engine_agent_dir}, "
              f"graph {graph_agent_dir / 'amg'}")
        place_engine(engine_agent_dir, agent_dir, entrypoint, scope, env)
        print(f"  engine  amg-* skills/{' + agents/' if kind != 'codex' else ''} "
              f"-> {engine_agent_dir} (other skills kept)")

        # The entry block depends on the environment: Claude Code = skill + hook + command
        # block; Codex = skill-aware block (skills + TOML subagents, no Claude hooks/command);
        # any other AGENTS.md env = the portable skill-less block.
        tpl = {"claude-code": "CLAUDE.md", "codex": "AGENTS.codex.md",
               "generic": "AGENTS.md"}[kind]
        block = render_control_text(_block_body((REPO / "entrypoint" / tpl).read_text(
            encoding="utf-8")), agent_dir, entrypoint, scope)
        inject_block(entry_path, block)
        label = {"claude-code": "skill-based", "codex": "skill-aware codex",
                 "generic": "skill-less / portable"}[kind]
        print(f"  block   {entrypoint} ({label}) -> {entry_path}")

        if kind == "claude-code":
            settings_tpl = render_control_text(
                (REPO / "entrypoint" / "settings.json").read_text(encoding="utf-8"),
                agent_dir, entrypoint, scope)
            merge_settings(engine_agent_dir / "settings.json", json.loads(settings_tpl))
            print(f"  hooks   merged -> {engine_agent_dir / 'settings.json'}")
            cmd_src = REPO / "entrypoint" / "commands"
            if cmd_src.is_dir():
                cmd_dest = engine_agent_dir / "commands"
                cmd_dest.mkdir(parents=True, exist_ok=True)
                for f in sorted(cmd_src.glob("*.md")):
                    cmd_dest.joinpath(f.name).write_text(
                        render_control_text(f.read_text(encoding="utf-8"), agent_dir, entrypoint, scope),
                        encoding="utf-8")
                print(f"  command /amg -> {cmd_dest}")
        elif kind == "codex":
            print("  env     codex (skill-aware): the SessionStart/SessionEnd hooks and the "
                  "/amg command are Claude-Code-only and were NOT written; the model drives the "
                  "loop via skills + the TOML subagents below, and reads the digest itself.")
        else:  # generic
            print("  env     skill-less: the SessionStart/SessionEnd hooks and the /amg "
                  "command are Claude-Code-only and were NOT written; the block drives the "
                  "loop with direct script calls (the digest is read, not @import-ed).")

    wrote = write_config(graph_agent_dir / "amg", agent_dir, entrypoint,
                         mirror, absorb, exclude, scalars)
    print(f"  config  {graph_agent_dir / 'amg' / 'config.yml'} "
          f"({'written' if wrote else 'kept existing — not clobbered'})")
    seed_digest(graph_agent_dir / "amg")

    # Render the models block (audit 1.14): Claude Code -> per-role model/effort into the
    # .md agent frontmatter; Codex -> TOML subagents (model + model_reasoning_effort); a
    # skill-less generic env runs one model, so tiering is inert there.
    if not project_only and _env_kind(env) != "generic":
        if yaml is None:
            print("  models  skipped (PyYAML not importable; reinstall after pip install pyyaml)")
        elif _env_kind(env) == "codex":
            render_codex_agents(REPO / "agents", engine_root / ".codex" / "agents",
                                _read_models(graph_agent_dir / "amg" / "config.yml"), env)
        else:
            render_agent_models(engine_agent_dir / "agents",
                                _read_models(graph_agent_dir / "amg" / "config.yml"), env)

    if deps:
        install_deps(deps)
    if verify:
        rc = verify_store(engine_agent_dir, graph_agent_dir)
        print(f"  verify  store {'clean' if rc == 0 else 'reported issues (see above)'}")
    if build:
        build_graph(engine_agent_dir, target, graph_agent_dir)

    if build:
        print("done. Structural graph built; run the amg-bootstrap skill (or just give a "
              "task) for semantic enrichment — summaries + edges, which need the model.")
    elif scalars.get("active", "true").lower() in ("true", "on", "yes"):
        print("done. AMG is ACTIVE but the graph is NOT built yet — `/amg on` only sets the "
              "flag. It builds on your first task in a NEW session, or now via `/amg sync` "
              "(or re-run install with --build).")
    else:
        print("done. AMG installed but inactive — `/amg on` to activate, then `/amg sync`.")


def uninstall(target: Path, agent_dir: str, entrypoint: str,
              scope: str, purge_graph: bool) -> None:
    target = target.resolve()
    engine_root = Path.home() if scope == "global" else target
    engine_agent_dir = engine_root / agent_dir
    entry_path = engine_root / entrypoint

    # 1. strip the activation block, keep the user's content
    if entry_path.exists():
        text = entry_path.read_text(encoding="utf-8")
        new = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", "", text, flags=re.S)
        entry_path.write_text(new.rstrip() + "\n" if new.strip() else "", encoding="utf-8")
        print(f"  block   removed from {entry_path}")
    # 2. remove only AMG skills/agents (the dir may hold the user's other skills)
    for sk in SKILL_NAMES:
        shutil.rmtree(engine_agent_dir / "skills" / sk, ignore_errors=True)
    for ag in (engine_agent_dir / "agents").glob("amg-*.md") if (engine_agent_dir / "agents").is_dir() else []:
        ag.unlink()
    cmd = engine_agent_dir / "commands" / "amg.md"
    if cmd.exists():
        cmd.unlink()
    codex_agents = engine_root / ".codex" / "agents"     # codex install: TOML subagents
    if codex_agents.is_dir():
        for tf in codex_agents.glob("amg-*.toml"):
            tf.unlink()
    print(f"  engine  amg-* skills/agents/commands removed from {engine_agent_dir}")
    # 3. drop AMG hooks from settings.json, keep the rest
    settings = engine_agent_dir / "settings.json"
    if settings.exists():
        try:
            obj = json.loads(settings.read_text(encoding="utf-8"))
            for event, entries in (obj.get("hooks") or {}).items():
                obj["hooks"][event] = [e for e in entries if not _is_amg_hook(e)]
            settings.write_text(json.dumps(obj, indent=2) + "\n", encoding="utf-8")
            print(f"  hooks   AMG hooks removed from {settings}")
        except (OSError, ValueError):
            pass
    # 4. the local graph is preserved unless explicitly purged
    graph = target / agent_dir / "amg"
    if purge_graph and graph.exists():
        shutil.rmtree(graph, ignore_errors=True)
        print(f"  graph   purged {graph}")
    else:
        print(f"  graph   kept {graph} (pass --purge-graph to remove)")
    print("done (uninstall).")


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #

def _parse(argv: List[str]) -> dict:
    args = {"target": None, "scope": "local", "agent_dir": None, "entrypoint": None,
            "env": "claude-code", "mirror": [], "absorb": [], "exclude": [], "scalars": {},
            "deps": [], "verify": True, "build": False, "project_only": False,
            "uninstall": False, "purge_graph": False}
    i = 0
    while i < len(argv):
        a = argv[i]
        if a == "--target":
            args["target"] = argv[i + 1]; i += 2
        elif a == "--scope":
            args["scope"] = argv[i + 1]; i += 2
        elif a == "--agent-dir":
            args["agent_dir"] = argv[i + 1]; i += 2
        elif a == "--entrypoint":
            args["entrypoint"] = argv[i + 1]; i += 2
        elif a == "--env":
            args["env"] = argv[i + 1]; i += 2
        elif a in ("--mirror", "--absorb", "--exclude"):
            args[a[2:]] = [s for s in argv[i + 1].split(",") if s.strip()]; i += 2
        elif a == "--set":                       # repeatable: --set key=value
            k, _, v = argv[i + 1].partition("=")
            args["scalars"][k.strip()] = v.strip(); i += 2
        elif a == "--deps":
            args["deps"] = [s for s in argv[i + 1].split(",") if s.strip()]; i += 2
        elif a == "--no-verify":
            args["verify"] = False; i += 1
        elif a == "--build":
            args["build"] = True; i += 1
        elif a == "--project-only":
            args["project_only"] = True; i += 1
        elif a == "--uninstall":
            args["uninstall"] = True; i += 1
        elif a == "--purge-graph":
            args["purge_graph"] = True; i += 1
        else:
            i += 1
    return args


def main(argv: List[str]) -> int:
    if not argv or "-h" in argv or "--help" in argv:
        print(__doc__)
        return 0
    a = _parse(argv)
    if not a["target"]:
        print("install.py: --target <project> is required.\n", __doc__)
        return 2
    target = Path(a["target"])
    # agent_dir / entrypoint default to the environment's convention when not given:
    # Claude Code -> .claude / CLAUDE.md; codex and other AGENTS.md envs -> .agents / AGENTS.md.
    kind = _env_kind(a["env"])
    agent_dir = a["agent_dir"] or (".claude" if kind == "claude-code" else ".agents")
    entrypoint = a["entrypoint"] or ("CLAUDE.md" if kind == "claude-code" else "AGENTS.md")
    if a["uninstall"]:
        uninstall(target, agent_dir, entrypoint, a["scope"], a["purge_graph"])
        return 0
    install(target, a["scope"], agent_dir, entrypoint,
            a["mirror"], a["absorb"], a["exclude"], a["scalars"], a["deps"], a["verify"],
            build=a["build"], project_only=a["project_only"], env=a["env"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
